### ISSUE TITLE
Periods options only works a few of them

### ISSUE THREAD

**Issue by kenzopanel** [awssat/laravel-visits#89]
I only can use period option [day, week, month, year] when count visitor. I can't use anything else than that, like minute, hours, ...

**Comment by BSN4** [comment]
@kenzopanel 

in visits.php config file you have option to define any period 

```php
    /*
    |--------------------------------------------------------------------------
    | Counters periods
    |--------------------------------------------------------------------------
    |
    | Record visits (total) of each one of these periods in this set (can be empty)
    |
    */
    'periods' => [
        'day',
        'week',
        'month',
        'year',
    ],
```

**Comment by kenzopanel** [comment]
how to add custom period? I want to add 'yesterday' period

**Comment by jarwonozt** [comment]
> @kenzopanel
> 
> in visits.php config file you have option to define any period
> 
> ```
>     /*
>     |--------------------------------------------------------------------------
>     | Counters periods
>     |--------------------------------------------------------------------------
>     |
>     | Record visits (total) of each one of these periods in this set (can be empty)
>     |
>     */
>     'periods' => [
>         'day',
>         'week',
>         'month',
>         'year',
>     ],
> ```


I tried all periods, but the calculation results are all the same, so today the results are the same this week and month.

**Comment by abdumu** [comment]
periods options are mentioned here: 
https://github.com/awssat/laravel-visits/blob/master/docs/8_clear-and-reset-values.md#periods-options

> how to add custom period? I want to add 'yesterday' period
as mentioned in the link above, You can  make your custom period -in your case, yesterday, by adding a carbon marco in AppServiceProvider. 

> I tried all periods, but the calculation results are all the same, so today the results are the same this week and month.
this might be because your records are new and of course data will be the same till the app collect more visits.

**Comment by abdumu** [comment]
periods options are mentioned here: 
https://github.com/awssat/laravel-visits/blob/master/docs/8_clear-and-reset-values.md#periods-options

> how to add custom period? I want to add 'yesterday' period
as mentioned in the link above, You can  make your custom period -in your case, yesterday, by adding a carbon marco in AppServiceProvider. 

> I tried all periods, but the calculation results are all the same, so today the results are the same this week and month.
this might be because your records are new and of course data will be the same till the app collect more visits.
